version: '2'

services:
    web:
        container_name: web
        build: .
        volumes:
            - .:/home/project-folder
        ports:
            - '8000:80'
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080